# Generated by Django 6.1.1 on 2026-09-12 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftlog',
            name='latitude_in',
        ),
        migrations.RemoveField(
            model_name='shiftlog',
            name='longitude_in',
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee'),
        ),
    ]
