# Generated by Django 6.1.1 on 2026-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_shiftlog_latitude_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employees/documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_pictures/'),
        ),
    ]
