# Generated by Django 6.1.1 on 2026-09-13 11:29
# add at the top of the migration file
from django.db import migrations
from django.db import migrations, models

def forwards(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    # Where the old boolean was False, mark terminated.
    Employee.objects.filter(is_active=False).update(status='terminated')
    # Where it was True, ensure active.
    Employee.objects.filter(is_active=True).update(status='active')


def backwards(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(status='terminated').update(is_active=False)
    Employee.objects.filter(status='active').update(is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '<previous_migration_name>'),
    ]

    operations = [
        # 1. Add the new column FIRST (nullable/no default issues)
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('on_leave', 'On leave'),
                         ('terminated', 'Terminated')],
                default='active', max_length=20, db_index=True,
            ),
        ),
        # 2. Copy data from is_active to status
        migrations.RunPython(forwards, backwards),
        # 3. Drop is_active
        migrations.RemoveField(model_name='employee', name='is_active'),
        # 4. Add remaining lifecycle fields
        migrations.AddField(
            model_name='employee', name='terminated_at',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='employee', name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_document_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='terminated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
