# Generated by Django 6.1.1 on 2026-09-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_is_active_employee_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('annual', 'Annual Leave')], max_length=20)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('entitled_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('adjustment_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', '-year', 'leave_type'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
