# Generated by Django 6.1.1 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('region', models.CharField(choices=[('HK', 'Hong Kong SAR'), ('CN', 'Mainland China'), ('MO', 'Macau SAR'), ('TW', 'Taiwan')], db_index=True, max_length=2)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['region', 'year'], name='employees_h_region_079fc1_idx')],
                'unique_together': {('date', 'region')},
            },
        ),
    ]
